### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Eldemarkki**

### CODE REVIEW

**Comment by Eldemarkki** [comment]
Don't merge yet, there seems to be some problem when trying to build the web project

**Comment by Eldemarkki** [comment]
I reverted back to Mantine 5 alpha, it seems have have fixed the build problem. When I tried installing the packages with NPM instead of Yarn, it seemed to fix it too, but I didn't commit that because we use Yarn. #111 could maybe fix it.

**Comment by Eldemarkki** [comment]
I think [this commit to Mantine](https://github.com/mantinedev/mantine/commit/a93abef62e536233ea87d0fdf320a81a936490ac) has caused the build the break

**Comment by Eldemarkki** [comment]
Fixed Mantine problems by manually installing some Emotion packages, https://v5.mantine.dev/changelog/5-0-0/#emotion-packages-as-peer-dependencies

**Review by kymppi — APPROVED** [review]

**Pull request merged**
